# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"import_data": "core.ipynb",
         "import_from_files": "core.ipynb",
         "import_from_csv": "core.ipynb",
         "create_tfidf": "core.ipynb",
         "get_phrases": "core.ipynb",
         "get_vectors": "core.ipynb",
         "assign_clusters": "core.ipynb",
         "reassign_hac_clusters": "core.ipynb",
         "reassign_kmeans_clusters": "core.ipynb",
         "visualize_clustering": "core.ipynb",
         "visualize_df": "core.ipynb",
         "get_cluster_topics": "core.ipynb",
         "recluster": "core.ipynb",
         "get_doc_topics": "core.ipynb",
         "evaluate": "core.ipynb",
         "score_phrase": "internal.ipynb",
         "score_token": "internal.ipynb",
         "get_phrase": "internal.ipynb",
         "get_vector_tfidf": "internal.ipynb",
         "get_vector_w2v": "internal.ipynb",
         "w2v_pretrained": "internal.ipynb",
         "get_cluster_assignments_hac": "internal.ipynb",
         "get_silhouette_score_hac": "internal.ipynb",
         "get_tree_height": "internal.ipynb",
         "get_optimal_height": "internal.ipynb",
         "get_clusters_hac": "internal.ipynb",
         "get_silhouette_score_kmeans": "internal.ipynb",
         "get_optimal_k": "internal.ipynb",
         "get_cluster_assignments_kmeans": "internal.ipynb",
         "get_clusters_kmeans": "internal.ipynb",
         "get_topics_from_docs": "internal.ipynb",
         "df_to_disk": "internal.ipynb",
         "sentences_to_disk": "internal.ipynb",
         "write_cluster": "internal.ipynb",
         "clusters_to_disk": "internal.ipynb",
         "process_sentence": "preprocessing.ipynb",
         "process_doc": "preprocessing.ipynb",
         "decontracted": "preprocessing.ipynb",
         "get_stop_words": "preprocessing.ipynb",
         "token_filter": "preprocessing.ipynb",
         "get_tokens": "preprocessing.ipynb",
         "tokenize_and_stem": "preprocessing.ipynb"}

modules = ["core.py",
           "internal.py",
           "preprocessing.py"]

doc_url = "https://VCUWrightCenter.github.io/TopEx/"

git_url = "VCUWrightCenter"

def custom_doc_links(name): return None
