# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"import_docs": "Core.ipynb",
         "sentences_to_disk": "Core.ipynb",
         "get_doc_top_phrases": "Core.ipynb",
         "get_doc_word_vectors_tfidf": "Core.ipynb",
         "get_doc_word_vectors_svd": "Core.ipynb",
         "get_doc_word_vectors_umap": "Core.ipynb",
         "get_doc_word_vectors_pretrained": "Core.ipynb",
         "get_doc_word_vectors_local": "Core.ipynb",
         "filter_sentences": "Core.ipynb",
         "get_optimal_k": "Core.ipynb",
         "get_cluster_assignments_kmeans": "Core.ipynb",
         "get_term_averages": "nlp_helpers.ipynb",
         "get_term_max": "nlp_helpers.ipynb",
         "get_top_phrases": "nlp_helpers.ipynb",
         "get_vec": "nlp_helpers.ipynb",
         "get_phrase_vec_tfidf": "nlp_helpers.ipynb",
         "get_phrase_vec_w2v": "nlp_helpers.ipynb",
         "average_sent_size": "nlp_helpers.ipynb",
         "w2v_from_corpus": "nlp_helpers.ipynb",
         "w2v_pretrained": "nlp_helpers.ipynb",
         "create_tfidf": "nlp_helpers.ipynb",
         "decontracted": "preprocessing.ipynb",
         "tokenize_and_stem2": "preprocessing.ipynb",
         "tokenize_and_stem": "preprocessing.ipynb"}

modules = ["core.py",
           "nlp_helpers.py",
           "preprocessing.py"]

doc_url = "https://etfrenchvcu.github.io/medtop/"

git_url = "https://github.com/etfrenchvcu/medtop/tree/master/"

def custom_doc_links(name): return None
