# AUTOGENERATED! DO NOT EDIT! File to edit: helpers.ipynb (unless otherwise specified).

__all__ = ['get_cluster_sent_coords']

# Cell
from nbdev.imports import *
from nbdev.export import *
import numpy as np

# Cell
def get_cluster_sent_coords(cluster_id, just_phrase_ids, cluster_assignments):
    "Parse (doc_id, sent_id) 'coordinate' pairs"
    #QUESTION: I removed the condition len(x.split(".")) > 1 is there a case when that wouldn't be True?
    cluster_mask = np.asarray(cluster_assignments) == cluster_id
    # TODO: Consolidate the next two lines if Amy's okay with storing just_phrase_ids as a list of tuples
    topic_labels = np.asarray(just_phrase_ids)[cluster_mask]
    sent_coords = [[int(x.split(".")[1]), int(x.split(".")[3])] for x in topic_labels]
    return sent_coords