# AUTOGENERATED! DO NOT EDIT! File to edit: nlp_helpers.ipynb (unless otherwise specified).

__all__ = ['get_term_max', 'w2v_pretrained']

# Cell
import gensim
from .preprocessing import *
import nltk
import numpy
import os
from textblob import TextBlob

# Cell
def get_term_max(tdm):
    avg_vec = numpy.zeros(len(tdm))
    for i in range(0,len(tdm)):
        avg_vec[i] = max(tdm[i])

    return(avg_vec)

# Cell
def w2v_pretrained(bin_file):
    return gensim.models.KeyedVectors.load_word2vec_format(bin_file, binary=True)